[tool.poetry]
name = "rpg"
version = "0.1.0"
description = ""
authors = ["veena"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
